### ISSUE TITLE
Security release pre-alert

### ISSUE THREAD

**Issue by juanarbol** [nodejs/tweet#100]
Security release pre-alert:

We will release new versions of 14.x, 16.x, 18.x, and 19.x release lines on or shortly
after Thursday, November 3, 2022 in order to address:

- 2 high severity issues
- 1 moderate severity issues

https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/

**Comment by Trott** [comment]
@joesepi @rginn @kyliewd

**Comment by Trott** [comment]
https://twitter.com/nodejs/status/1587593619485392896

**Comment by Trott** [comment]
Thanks, @rginn!
