### ISSUE TITLE
Security Release available

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/tweet#101]
Security release:

New security releases are now available for versions v14, v16, v18, and v19 of Node.js.

https://nodejs.org/en/blog/vulnerability/november-2022-security-releases

**Comment by RafaelGSS** [comment]
**We're still promoting v18. @juanarbol will update this issue when is ready to tweet**

**Comment by RafaelGSS** [comment]
Ready to go when https://github.com/nodejs/nodejs.org/pull/4916 merge

**Comment by juanarbol** [comment]
https://twitter.com/nodejs/status/1588646038092513288

cc @RafaelGSS could please close this?
