### ISSUE TITLE
Process for merging tweets faster

### ISSUE THREAD

**Issue by joesepi** [nodejs/tweet#44]
Related: #40 

First question: is only one approval from a member of the @nodejs/social team adequate to merge a tweet. I assume yes, but we should clarify in our docs.

Also: should we setup a github action that merges a tweet within 24hrs of one approval or should we just rely on the fact that once a social team member approves, they can merge. If we setup a 24hr github action, we could build it as such that it would tweet at an optimal time/day.

**Comment by bnb** [comment]
> is only one approval from a member of the @nodejs/social team adequate to merge a tweet.

I'd assume yes. I also don't think that any other smaller groups like this document how many approvals are required.

> should we setup a github action that merges a tweet within 24hrs of one approval or should we just rely on the fact that once a social team member approves, they can merge. 

I don't think a GitHub action is required here, given that a social team member will be clicking one green button to approve already... I don't think asking them to click another is a big deal.

**Comment by joesepi** [comment]
I'm satisfied with this discussion. Closing issue. :)
