### ISSUE TITLE
`multipleResolves` poll

### ISSUE THREAD

**Issue by mmarchini** [nodejs/tweet#65]
Ref to https://github.com/nodejs/node/issues/41554

I would like to send the following poll through the `@nodejs` account to get a good amount of engagement that allows us to understand if there's any interest to keep the `multipleResolves` event, or if there are use cases we missed.

```
We're considering deprecating `process.on('multipleResolves'`, but first we would like to gauge the community's familiarity with and usage of 'multipleResolves'

You can help us by answering to the pool below, and if you have used it, please share your experience in a reply

- Unfamiliar with it
- Familiar but not using
- Used before but not now
- Currently using it
```

The 25 characters limit in each choice option makes it difficult to write a better poll. If folks have a better idea for choices, please feel free to share.

**Comment by joesepi** [comment]
@mmarchini - we can be creative when we put this out. Perhaps expand in a thread if any more context is needed in the setup or poll answers.

**Comment by bnb** [comment]
slightly tweaked the language: 

```
We're considering deprecating `process.on('multipleResolves')`, but we want to gauge the community's familiarity with and usage of 'multipleResolves' before doing so.

Could you select whichever is true of your experience with 'multipleResolves'? 💚
```
![image](https://user-images.githubusercontent.com/502396/150878493-06b1f5b5-0f1d-404e-b68c-c965927d82fd.png)

**Comment by joesepi** [comment]
How long do we want the poll to run @mmarchini @bnb ?

**Comment by bnb** [comment]
You're going to see diminishing returns as the tweet slips out of getting engagement. I'd honestly just leave it up for 24 hours.

**Comment by joesepi** [comment]
We could quote tweet ourselves in 24hrs to re-boost it? We could try to promote it through something like Node Weekly?

I just dont know how much data @mmarchini and the team are looking to get.

All that being said, I'm fine with whatever.

**Comment by bnb** [comment]
I'm happy to put it up for 7 days if we'd like. It'd be good to note how many replies we have at 24 hours vs. at the end to see if we do actually get substantially more responses and if they change the result or not.

**Comment by mmarchini** [comment]
7 days sound good if we can promote it via Node Weekly, otherwise I'm fine with 24-48 hours.

**Comment by joesepi** [comment]
Tweet went out: https://twitter.com/nodejs/status/1486045217635643396

![image](https://user-images.githubusercontent.com/143668/155350049-b756541c-7607-4872-9847-81e5a84ec442.png)

**Comment by joesepi** [comment]
I'll close this issue @mmarchini -- I hope this poll was useful. :)
