### ISSUE TITLE
Automated tweets when Node.js LTS version gets close to end-of-life

### ISSUE THREAD

**Issue by trivikr** [nodejs/tweet#78]
### Is your feature request related to a problem? Please describe.
There's no system to tweet about EOL versions of Node.js
The tweets need to be manually created like https://github.com/nodejs/tweet/pull/77

### Describe the solution you'd like
Create automated tweets when a Node.js LTS version reaches close to EoL.
The end-of-life dates can be set from Release Schedule like https://github.com/nodejs/Release#release-schedule

It can start tweeting as a countdown before EOL dates, like:
* 3 months
* 1 month
* 1 week
* 3 days
* 0 day

There are existing scripts for recurring tweets for example https://github.com/nodejs/tweet/tree/main/scripts/recurring

### Describe alternatives you've considered
Manually remembering about EOL, and creating PR like in https://github.com/nodejs/tweet/pull/77

### Additional context
This question was asked [on #nodejs slack](https://openjs-foundation.slack.com/archives/CK9Q4MB53/p1652212827121889), and here are some comments:

@Qard says
> Automating tweets for LTS expiry sounds like a good idea to me. It'd be really great if we could get more users off super old versions. :sweat_smile:

@joesepi says
> Sounds like a great idea. automate all the things

**Comment by hemanth** [comment]
👍  We already have the [schedule.json](https://raw.githubusercontent.com/nodejs/Release/main/schedule.json) with us.

**Comment by joesepi** [comment]
This would be great.
